### PR TITLE
Apache Portable Runtime

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
Due to deficiencies in Centos 7/OEL 7 I either need to create an openssl role or this is a difficult problem to solve.

Basically we need greater than 1.0.2 and that update has not occured on those distros through any normal release channels. Fedora works, so the fix is coming but its not here now.

Perhaps an APR boolean for these distros?

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
While this now works, I'm afraid that it will break several Operating Systems due to the install location. Looking to install in a secondary location then build APR using that seperate location, then use tomcat native using that separate native as well. As that would be ideal.

Upstream Dependencies for this superior tomcat are. Does anyone have experience with this that might guide me finishing off this block?

[OpenSSL Role](https://github.com/ChristopherDavenport/ansible-role-openssl)  
[Apache Portable Runtime Role](https://github.com/ChristopherDavenport/ansible-role-apr)

**Comment by ChristopherDavenport** [comment]
So I've managed to get this together. 

`tomcat_use_apr` is a new variable that will pull in apr and is set to true by default because it should be the default. Everything is installed to `/opt` with openssl, apr, and now tomcat. 

However everything works together in concert. 

So it will work like previously if the variable above is set to false.

Now is the time to raise objections.

**Comment by djkcel** [comment]
Great!

➜ service tomcat start
➜ service tomcat stop

INFO - Loaded APR based Apache Tomcat Native library 1.1.16.

It works with the Tomcat 9?

**Comment by ChristopherDavenport** [comment]
It does. If anyone wants to deal with the previous version I have released a tag for v0.1.0 which can be installed instead via 

```
ansible-galaxy install ChristopherDavenport,v0.1.0
```

However normal installation will install the new integrated components.

**Pull request merged**
